Enforce newline-per-chained-call rule and fix code style
cuttle-cards/cuttle pull request #1080
Opened 2024-10-06 15:36 UTC by Mang0codes

## Issue number

Relevant [issue number](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- Resolves #1019

## Please check the following

- [ ] Do the tests still pass? (see [Run the Tests](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#run-the-tests))
- [ ] Is the code formatted properly? (see [Linting (Formatting)](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#linting-formatting))
- For New Features:
  - [ ] Have tests been added to cover any new features or fixes?
  - [ ] Has the documentation been updated accordingly?

## Please describe additional details for testing this change

2024-10-06 20:51 UTC, itsalaidbacklife requested changes
This looks like the right idea but something is going wrong for it to say so many things are changing. It looks like the affected files are completely rewritten instead of having individual lines changed

2024-10-06 21:01 UTC, Mang0codes commented on .eslintrc.js
I think the issue might be with the Windows machine. You can check the latest commit to see the changes, or I can raise another PR if you'd prefer.

2024-10-07 13:01 UTC, itsalaidbacklife commented on .eslintrc.js
@Mang0codes that makes sense. It is something that I thought/hoped we'd standardized such that this wouldn't happen when windows users submit updates, but it looks like either it wasn't previously done, or wasn't done correctly. For the moment, could you try reimplementing the change using WSL (windows subsystem linux) to standardize line endings to the unix ones)? 

I'm writing up an issue to fix this

2024-10-07 13:22 UTC, itsalaidbacklife commented on .eslintrc.js
@Mang0codes I've written up #1082 to fix this issue. If you'd like, you could tackle that issue first yourself and then that might fix this issue here

2024-10-07 18:45 UTC, closed without merging