Enhancement: move logout button to the bottom for mobiles (closes #135)
cuttle-cards/cuttle pull request #139
Opened 2022-10-08 08:10 UTC by chikaldirick

## Please check the following

- [x] Do the tests still pass? (see [Run the Tests](https://github.com/cuttle-cards/cuttle#run-the-tests))
- [x] Is the code formatted properly? (see [Linting (Formatting)](https://github.com/cuttle-cards/cuttle#linting-formatting))

## Please describe additional details for testing this change
This is a tiny UI improvement that moves logout link from the very top to the bottom for mobile screens. (closes #135)
P.S. I decided to make things more simple and straightforward in terms of `pageLinks` generation depending on authentication status and screen size. If you want to keep thing as short as it possible we may use a rest spread operator approach of `...(cond ? {a: 1} : {}),` but I'm not sure it'll be readable then.

2022-10-08 17:39 UTC, itsalaidbacklife commented
Looks like we're failing lint. @chikaldirick can you run `npm run lint:fix` and commit the changes?

2022-10-08 17:41 UTC, chikaldirick commented
> Looks like we're failing lint. @chikaldirick can you run `npm run lint:fix` and commit the changes?

Sure, will do now.

2022-10-08 17:50 UTC, chikaldirick commented
@itsalaidbacklife, thanks for your comment.
I have resolved prettier errors locally (most of them were related to the extra indentation level and one suggested to put all `<v-list-item>` attributes to a single line.

2022-10-09 13:25 UTC, seriouslysean requested changes
Looking at this as a whole, I think we might need to update the desktop version, too. @itsalaidbacklife would love some feedback here. @chikaldirick did great on the mobile version, but I can't help but think we might want something like this for desktop, too? Align the logout being on the bottom and either having the collapse link be below it, or move it out to something like this on desktop as a single control that we can remove on mobile?

![image](https://user-images.githubusercontent.com/414475/194759381-adc87060-3ee3-47d4-a8ae-c9259db01a18.png)

2022-10-12 15:08 UTC, seriouslysean requested changes
@chikaldirick whoops, approved too quickly. I double checked all of this locally and the logout link is showing whether you're logged in or not and twice on mobile devices.

| desktop | desktop | mobile | mobile |
| -------- | -------- | ------- | ------- |
| ![image](https://user-images.githubusercontent.com/414475/195379765-1e40fd42-9209-4171-97fa-7ae867591073.png) | ![image](https://user-images.githubusercontent.com/414475/195379826-db1ad5d1-739a-4221-b294-a6edb224264b.png) | ![image](https://user-images.githubusercontent.com/414475/195379866-a971adc9-6f41-4f1a-aecb-3a2752a7b99a.png) | ![image](https://user-images.githubusercontent.com/414475/195379915-2ab4bd00-a39d-4e29-9236-0d74464b0749.png) |

2022-10-12 15:10 UTC, seriouslysean commented on client/js/components/NavigationDrawer.vue
> +      <v-list v-if="isSmallDevice">
This should only show if isSmallDevice and  not authenticated.

2022-10-26 17:11 UTC, closed without merging