Update (and Remove) Dependencies
cuttle-cards/cuttle pull request #47
Opened 2022-06-27 21:41 UTC by seriouslysean

## Please check the following

- [ ] Do the tests still pass? (see [Run the Tests](https://github.com/cuttle-cards/cuttle#run-the-tests))
- [x] Is the code formatted properly? (see [Linting (Formatting)](https://github.com/cuttle-cards/cuttle#linting-formatting))
- For New Features:
  - [x] Have tests been added to cover any new features or fixes?
  - [x] Has the documentation been updated accordingly?

## Please describe additional details for testing this change

2022-06-27 21:45 UTC, seriouslysean reviewed
I also removed those deprecated unit tests.

2022-06-27 21:45 UTC, seriouslysean commented on config/globals.js
> + * See: https://sailsjs.com/documentation/reference/configuration/sails-config-globals
Modified this since the old file isn't even there anymore with a link to the global config help page.

2022-06-27 21:45 UTC, seriouslysean commented on package.json
> -    "chai-as-promised": "^5.3.0",
No usage as far as I was able to see. I also removed the bootstrap test file.

2022-06-27 21:45 UTC, seriouslysean commented on package.json
> -    "ejs": "2.5.5",
No usage as far as I was able to see. The only ref to `ejs` is commented out.

2022-06-27 21:45 UTC, seriouslysean commented on package.json
> +  "version": "3.0.2",
I know we recently did some dev upgrades, might be worth bumping this to a new version soon. I know it's not a big "app" feature, but there's an argument to be made for a 3.1.X release.

2022-06-29 23:59 UTC, seriouslysean reviewed
@itsalaidbacklife a lot of the changes are innocuous and only spacing changes or very minor syntax adjustments. We may want to turn off the build failing if linting doesn't pass for a bit to get this in, and then do a follow up to fix all remaining issues.

I may take another crack at it this week though and just finish them all up.

2022-06-29 23:59 UTC, seriouslysean commented on .eslintrc.js
> +};
Shared between Cypress and Jest.

2022-06-29 23:59 UTC, seriouslysean commented on package.json
> +    "_lint": "vue-cli-service lint --ext .js,.ts,.vue .",
Shared script to call the Vue cli linter.

2022-06-29 23:59 UTC, seriouslysean commented on package.json
> +    "lint": "npm run _lint -- --no-fix",
Calls the vue cli lint script but passes no-fix so we don't do that by default.

2022-06-29 23:59 UTC, seriouslysean commented on package.json
> +    "lint:fix": "npm run _lint -- --fix",
Calls the vue cli lint script but passes fix so we actively need to choose to do that.

2022-07-01 10:42 UTC, itsalaidbacklife commented on api/controllers/game/concede.js
> -const Promise = require('bluebird');
Goodnight, sweet prince

2022-07-03 01:11 UTC, itsalaidbacklife requested changes
Looks great! Couple minor change requests

2022-07-03 01:38 UTC, itsalaidbacklife commented on client/js/components/StatsLeaderboard.vue
> +        const { ...weeks } = playerWins;
`stats.spec.js` should be updated to detect this regression.  Relevant test is
```
it('Displays Headers, Cards, and Table', () => {
// ...
//data table
cy.get('[data-week-total=Player2]').contains('W: 5, P: 9'); // add this line
```

2022-07-03 01:42 UTC, itsalaidbacklife commented on client/js/views/GameView.vue
> -        default:
Down scoping

2022-07-03 01:43 UTC, itsalaidbacklife commented on client/js/components/StatsLeaderboard.vue
> +        const { ...weeks } = playerWins;
This will likely require an update to the [no-unused-vars rule](https://eslint.org/docs/latest/rules/no-unused-vars) to add a varsIgnorePattern

2022-07-03 14:53 UTC, itsalaidbacklife commented on client/js/components/StatsLeaderboard.vue
> +        const { ...weeks } = playerWins;
Going with delete for now

2022-07-03 15:03 UTC, seriouslysean commented on client/js/components/StatsLeaderboard.vue
> +        const { ...weeks } = playerWins;
Skipping on this for now in lieu of a delete, can revisit later. Tests pass again with your addition (and I confirmed it fails).
![image](https://user-images.githubusercontent.com/414475/177045621-f6cd36dc-bb4b-4e88-be7f-438a9e840e98.png)
![image](https://user-images.githubusercontent.com/414475/177045624-be0fa973-b4be-4359-85cb-703365631f59.png)

2022-07-03 15:03 UTC, seriouslysean commented on client/js/components/StatsLeaderboard.vue
> +        debugger;
Removed

2022-07-03 15:05 UTC, seriouslysean commented on client/js/views/LoginSignup.vue
> +    <img id="logo" alt="Cuttle logo" src="../img/logo.png" />
Invalid in html4, valid in html5 as far as I can tell. https://github.com/prettier/prettier/issues/5992#issuecomment-474857121

2022-07-03 20:37 UTC, itsalaidbacklife approved these changes
Great work

2022-07-03 20:59 UTC, itsalaidbacklife reviewed
All good except the .only()

2022-07-03 20:59 UTC, itsalaidbacklife commented on tests/e2e/specs/out-of-game/stats.spec.js
> +  it.only('Displays Headers, Cards, and Table', () => {
Stage only

2022-07-03 21:00 UTC, seriouslysean commented on tests/e2e/specs/out-of-game/stats.spec.js
> +  it.only('Displays Headers, Cards, and Table', () => {
```suggestion
  it('Displays Headers, Cards, and Table', () => {
```

2022-07-03 21:21 UTC, merged