fix: reorganized components
cuttle-cards/cuttle pull request #562
Opened 2023-09-06 23:47 UTC by arnaut08

## Issue number #546

Relevant #546
- Resolves #546

## Please check the following

- [x] Do the tests still pass? (see [Run the Tests](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#run-the-tests))
- [x] Is the code formatted properly? (see [Linting (Formatting)](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#linting-formatting))
- For New Features:
  - [ ] Have tests been added to cover any new features or fixes?
  - [ ] Has the documentation been updated accordingly?

## Please describe additional details for testing this change
I don't think additional details are required as it's just the reorganization of the components files.

2023-09-07 00:05 UTC, seriouslysean requested changes
Solid work so far! I think this is headed mostly in the right direction but I have a lot of thoughts on how I think we should be separating everything.

Considering how we utilize the components, it makes sense to me to split by route for now, and then organizing within route based folders.

Something like this:

/routes/

    - /home/
        - /components
        - /js
    - /about/
        - /components
        - /js

Etc, which would allow us to code split by route if we so choose by doing async imports. It also would keep a logical separation of components we use within those pages and would could set up route based aliases in vite. Any shared functionality would live under some sort of core, or global namespace.

@itsalaidbacklife penny for your thoughts.

2023-09-07 00:36 UTC, arnaut08 commented
> Considering how we utilize the components, it makes sense to me to split by route for now, and then organizing within route based folders.
> 
> Something like this:
> 
> * /routes/
>   
>   * /home/
>     
>     * /components
>     * /js
>   * /about/
>     
>     * /components
>     * /js

Currently we have all the views(route specific files) inside the /views directory. As per my understanding, you're asking for us to split the files as per the routes. So we'll have a /routes directory and individual directories for each route with respective view file, and respective components grouped in the components directory, right? 
Something like this:
- Main view file - /routes/home/HomeView.vue
- Respective component files - /routes/home/Components/...

Also, what exactly is the js subdirectory for? Is it for respective utility function files?

2023-09-07 11:03 UTC, seriouslysean commented
> Also, what exactly is the js subdirectory for? Is it for respective utility function files?

@arnaut08 exactly that. Utilities, store files, or anything other js imports related to just that route. You may not need the folder if the route doesn't have any right now, though.

I'll file a follow up to look in to async importing the top level Vue files from the router to garner the benefit from the file restructure.

2023-09-07 22:59 UTC, seriouslysean requested changes
This is super close! Convert  all the relative paths to aliases and in the vite config make an entry for the new areas; core, and each route as a top level so you can do something like `~core/components/FileName.Vue`.

2023-09-07 22:59 UTC, seriouslysean commented on src/core/components/TheHeader.vue
> +import { getPageLinks } from '../composables/navLink.js';
This should stay an alias

2023-09-07 22:59 UTC, seriouslysean commented on src/routes/game/components/ChooseWhetherToCounterDialog.vue
> +import GameCard from './GameCard.vue';
These should stay aliases, too

2023-09-07 22:59 UTC, seriouslysean commented on src/routes/game/components/GameDialogs.vue
> +import CannotCounterDialog from './CannotCounterDialog.vue';
These should stay aliases

2023-09-07 22:59 UTC, seriouslysean commented on src/routes/game/components/GameUnavailableView.vue
> +import ReauthenticateDialog from './ReauthenticateDialog.vue';
Keep as alias

2023-09-07 22:59 UTC, seriouslysean commented on src/routes/game/components/GameUnavailableView.vue
>  import GameUnavailableOverlay from './GameUnavailableOverlay.vue';
Convert to alias

2023-09-14 13:17 UTC, itsalaidbacklife commented
@arnaut08 sorry to have left this hanging. This is looking good. I need to sync up with @seriouslysean and give this a look together but we should have the final feedback for you by end of week

2023-09-14 18:18 UTC, arnaut08 commented
Sorry for the delayed response. I've made the changes suggested by @seriouslysean. Please review those changes and consider them for the feedback. Thank you.

2023-09-25 14:08 UTC, itsalaidbacklife reviewed
This is a great start. I apologize that it's taken so long to get a full review on this. It's a high impact restructuring so we wanted to make sure the internal team was in sync about the desired structure. I'm requesting a slight rework of how the folders are organized, and of removing the `~` aliases and sticking with `@` relative imports.

For the folder change, we will remove the `core` folder, and move both `core/components` and `core/composables` directly into `src/components` (for base components) and `src/composables` (for root composables).

Additionally, let's rename the `src/routes/auth` folder to `src/routes/login` as that's the name of the route. 

Again, great work! This will add a lot of value, especially making it easier for new contributors to find components while onboarding. Thanks for your contribution! Please comment here (or join us on [discord](https://discord.gg/6vQCFa6nvP)) if you have any questions.

2023-09-25 14:08 UTC, itsalaidbacklife commented on src/routes/game/components/SevenDoubleJacksDialog.vue
> +import GameCard from './GameCard.vue';
Let's stick to imports from `'@'` for flexibility in case files are moved around

2023-10-09 17:50 UTC, itsalaidbacklife commented
@arnaut08 are you still interested in finishing this task?

2023-10-09 17:56 UTC, arnaut08 commented
> @arnaut08 are you still interested in finishing this task?

Hey! I'm so sorry for the delayed response. Yes, I'll make the changes as per your latest comments.

2023-10-09 18:35 UTC, arnaut08 commented on src/core/components/UsernameToolTip.vue
This is being imported in `UsernameToolTip.stories.js` as well. Should I keep it in the `src/components` only or move it to `src/game/components`?

2023-10-09 23:59 UTC, itsalaidbacklife commented on src/core/components/UsernameToolTip.vue
Good question. The stories files are for storybook which is a separate tool that essentially instantiates components just to render them statically so you can see how they look. They don't count as real source code (since they're effectively a playground for instantiating components) and don't affect where we put components/how we think about which components belong where. So keep it in `src/game/components`

2023-10-11 12:51 UTC, itsalaidbacklife reviewed
@arnaut08 excellent work. This all looks right. I have two whitespace nitpicks in the comments. Other than that, the only thing to do is to fix the merge conflicts. Let me know if you'd like help navigating them. 

This is a great reorganization that I'm looking forward to finalizing. Thanks for your contribution!

2023-10-11 12:51 UTC, itsalaidbacklife commented on src/routes/home/components/GameListItem.vue
> +import GameStatus  from '_/utils/GameStatus.json';
nitpick: extra whitespace
```suggestion
import GameStatus from '_/utils/GameStatus.json';
```

2023-10-11 12:51 UTC, itsalaidbacklife commented on src/stores/gameList.js
> +import GameStatus  from '_/utils/GameStatus.json';
```suggestion
import GameStatus from '_/utils/GameStatus.json';
```

2023-10-11 17:10 UTC, itsalaidbacklife commented
@arnaut08 this is great. There are just two remaining merge conflicts due in 
```
src/components/HowItWorksDialog.vue
src/views/RulesView.vue
```
which were just updated today. Apologies that this has been a moving target. I can stop merging other PR's until this is done so that your update can go live before other things go in because you've been working on this for a while and it is so high-impact

2023-10-11 19:30 UTC, itsalaidbacklife approved these changes
Great work, thanks for taking this on!

2023-10-11 19:31 UTC, merged