Feature/616
cuttle-cards/cuttle pull request #728
Opened 2023-10-31 11:07 UTC by arnaut08

## 616

Relevant [issue number](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- Resolves #616

## Please check the following

- [x] Do the tests still pass? (see [Run the Tests](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#run-the-tests))
- [x] Is the code formatted properly? (see [Linting (Formatting)](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#linting-formatting))
- For New Features:
  - [ ] Have tests been added to cover any new features or fixes?
  - [ ] Has the documentation been updated accordingly?

## Please describe additional details for testing this change

2023-10-31 12:52 UTC, itsalaidbacklife requested changes
Nice work. I'm requesting a revision of the pluralization and to move the dialog strings into the `stats` block that's created in #727

2023-10-31 12:52 UTC, itsalaidbacklife commented on src/components/StatsScoringDialog.vue
> +          <span v-if="showButtonText">{{ t('game.dialogs.statsScoringDialog.ranksDetermination') }}</span>
@arnaut08 let's rename this string to `rankDetermination`
```suggestion
          <span v-if="showButtonText">{{ t('game.dialogs.statsScoringDialog.rankDetermination') }}</span>
```

2023-10-31 12:52 UTC, itsalaidbacklife commented on src/components/StatsScoringDialog.vue
> +            1 {{ t('game.dialogs.statsScoringDialog.points.singular') }}
We actually don't need a separate block for this, we can use i18n's pluralization system to specify the count like so 
```suggestion
            {{ t('game.dialogs.statsScoringDialog.points.displayName', 1) }}
```

Then we can correspondingly update all the other references to use this new definition and update the definition itself in the language files to specify the count and to use a different word for the singular version

2023-10-31 12:52 UTC, itsalaidbacklife commented on src/components/StatsScoringDialog.vue
> +            5 {{ t('game.dialogs.statsScoringDialog.points.displayName') }}
Let's refactor the points displayName to input a count and pluralize using the same key
```suggestion
            {{ t('game.dialogs.statsScoringDialog.points.displayName', 5) }}
```

2023-10-31 12:52 UTC, itsalaidbacklife commented on src/components/StatsScoringDialog.vue
> +            4 {{ t('game.dialogs.statsScoringDialog.points.displayName') }}
```suggestion
            {{ t('game.dialogs.statsScoringDialog.points.displayName', 4) }}
```

2023-10-31 12:52 UTC, itsalaidbacklife commented on src/components/StatsScoringDialog.vue
> +            3 {{ t('game.dialogs.statsScoringDialog.points.displayName') }}
```suggestion
            {{ t('game.dialogs.statsScoringDialog.points.displayName', 3) }}
```

2023-10-31 12:52 UTC, itsalaidbacklife commented on src/components/StatsScoringDialog.vue
> +            1 {{ t('game.dialogs.statsScoringDialog.points.singular') }}
You can see an example of this in ScoreGoalTooltip.vue in the `kingPoints` computed property which pluralizes the `game.score.kings` string

2023-10-31 12:52 UTC, itsalaidbacklife commented on src/components/StatsScoringDialog.vue
> +            2 {{ t('game.dialogs.statsScoringDialog.points.displayName') }}
```suggestion
            {{ t('game.dialogs.statsScoringDialog.points.displayName', 2) }}
```

2023-10-31 12:52 UTC, itsalaidbacklife commented on src/translations/en.json
> +          "singular": "Point",
We can apply `i18n` pluralization to address both of these with a single key
```suggestion
          "displayName": "1 Point | {count} Points",
```

2023-10-31 12:52 UTC, itsalaidbacklife commented on src/translations/es.json
> +          "singular": "Punto",
```suggestion
          "displayName": "1 Punto | {count} Puntos",
```

2023-10-31 12:52 UTC, itsalaidbacklife commented on src/translations/fr.json
> +          "singular": "Point",
```suggestion
          "displayName": "1 Point | {count} Points",
```

2023-10-31 12:52 UTC, itsalaidbacklife commented on src/translations/en.json
> +      "statsScoringDialog": {
This dialog isn't in the `GameView` so how about we move this whole block into the new `stats` block you've created in #727?

2023-11-09 13:58 UTC, itsalaidbacklife commented
@arnaut08 are you still interested in completing this issue?

2023-11-12 12:46 UTC, arnaut08 commented
Apologies for the delayed response. Yes, I'll cover those comments and push my changes in a couple of days.

2023-11-18 15:51 UTC, arnaut08 commented
I'm drafting this and the other PR of mine as I might not have enough time to work on the changes for now. But I'll try to work on them as soon as possible.

2024-06-28 17:53 UTC, itsalaidbacklife commented
Closing as stale

2024-06-28 17:53 UTC, closed without merging