prevent ranked-switch text to wrap, media query and padding adjustment
cuttle-cards/cuttle pull request #860
Opened 2024-01-16 10:38 UTC by Posoroko

## #859

Relevant [issue number](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- Resolves #

## Please check the following

## Please describe additional details for testing this change
- modified the media query so the text doesn't wrap between 966 and 980px
- added a media query to handle the same problem on  xxs screens ( < 350px)
- adjusted the padding on small screen so the element are displayed more evenly in the ranked-switch component.

2024-01-16 10:58 UTC, Posoroko commented
I feel he whole component could be styled in a much simpler way. Some simple flex-box would be enough to prevent the use of media queries.  But I'm not sure how customizable vuetify components are.

2024-01-16 13:21 UTC, Posoroko commented
@Haviles04 Probably.  I'm not used to styling vuetify components and how you guys handle it for cuttle.

2024-01-19 00:21 UTC, Haviles04 commented
> @Haviles04 Probably.  I'm not used to styling vuetify components and how you guys handle it for cuttle.  

Just put `text-wrap: nowrap` in the .rank-switch main style

2024-01-29 22:04 UTC, Haviles04 commented on src/routes/lobby/LobbyView.vue
> +}
I think it's better to put `flex-shrink-0` as a vuetify utility class directly on the v-swtich

2024-01-29 22:05 UTC, Haviles04 requested changes
Nice, this is a weird problem caused by Vuetify's styling. Nice catch though and good fix! The added media query for 350px definitely looks better to me! One small change requested to utilize Vuetifys utility classes

2024-02-01 12:23 UTC, Haviles04 approved these changes
Nice work @Posoroko!!

2024-02-01 13:09 UTC, merged