Store API Call Refactor
cuttle-cards/cuttle pull request #971
Opened 2024-06-18 00:05 UTC by Haviles04

## Issue number

Relevant [issue number](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- Resolves #

## Please check the following

- [ ] Do the tests still pass? (see [Run the Tests](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#run-the-tests))
- [ ] Is the code formatted properly? (see [Linting (Formatting)](https://github.com/cuttle-cards/cuttle/blob/main/docs/setup-development.md#linting-formatting))
- For New Features:
  - [ ] Have tests been added to cover any new features or fixes?
  - [ ] Has the documentation been updated accordingly?

## Please describe additional details for testing this change

2024-06-18 00:10 UTC, Haviles04 commented
There are a few more functions we could reduce by creating another generic function, but I'm not sure it's worth it for 1 or 2 functions

2024-06-18 12:42 UTC, itsalaidbacklife requested changes
Good idea and nice work

2024-06-18 12:42 UTC, itsalaidbacklife commented on src/stores/game.js
>        });
await removes the need for .then()

2024-06-18 12:42 UTC, itsalaidbacklife commented on src/stores/game.js
>        }).then(() => {
Remove .then()

2024-06-18 12:42 UTC, itsalaidbacklife commented on src/stores/game.js
> +      await this.handleAPIGet('resolveThree', { cardId, opId: this.opponent.id }).then(() => {
.then()

2024-06-18 12:42 UTC, itsalaidbacklife commented on src/stores/game.js
> +      await this.handleAPIGet('counter', { cardId: twoId, opId: this.opponent.id }).then(() => {
```suggestion
      await this.handleAPIGet('counter', { cardId: twoId, opId: this.opponent.id });
```

2024-06-18 12:42 UTC, itsalaidbacklife commented on src/stores/game.js
> +        opId: this.opponent.id,
.then

2024-06-18 12:42 UTC, itsalaidbacklife commented on src/stores/game.js
> +        opId: this.opponent.id,
.then()

2024-06-19 00:37 UTC, itsalaidbacklife approved these changes
Last nitpick and we're good

2024-06-19 00:37 UTC, itsalaidbacklife commented on src/stores/game.js
> +            data: body,
Let's use the shorthand here. For the same reason let's rename body to data
```suggestion
            method,
            url,
            data,
```

2024-06-19 03:16 UTC, merged